#!/bin/bash
#Place in ~/.local/bin/

synclient MinSpeed=0.9
synclient MaxSpeed=1.5

synclient VertScrollDelta=-113
synclient HorizScrollDelta=-113

synclient VertEdgeScroll=0
synclient HorizEdgeScroll=0
synclient HorizTwoFingerScroll=1

synclient PalmDetect=1

synclient CoastingSpeed=22.5
synclient CoastingFriction=0.05

synclient FingerLow=10
synclient FingerHigh=20

synclient ClickTime=65
