#!/bin/bash

VERSION="0.2"
FLAG_DL="FALSE"
FLAG_OPEN="FALSE"
FLAG_VEN="FALSE"

while getopts 'vdoe?' OPTION; do
    case "$OPTION" in
        v)
            echo "Debian Discord/Vencord update script version $VERSION"
            exit 1
            ;;
        d)
            FLAG_DL="TRUE"
            ;;
        o)
            FLAG_OPEN="TRUE"
            ;;
        e)
            FLAG_VEN="TRUE"
            ;;
        ?)
            echo "Usage: $(basename $0) [-v | [o &| e]]"
            exit 1
            ;;
    esac
done

if [ "FALSE" != $FLAG_DL ]; then
    echo "[Getting discord update package...]"
    wget https://discordapp.com/api/download?platform=linux -O ~/Downloads/discord.deb

    echo "[Installing update package...]"
    cd ~/Downloads/; sudo apt install ./discord.deb

    echo "[Cleaning up downloads directory]"
    rm ./discord.deb
else
    echo "[Skipping downloading new package]"
fi

if [ "FALSE" != $FLAG_VEN ]; then
    echo "[Opening Vencord UI...]"
    sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"
else
    echo "[Ignoring Vencord]"
fi

if [ "FALSE" != $FLAG_OPEN ]; then
    echo "[Opening Discord...]"
    discord
else
    echo "[Update finished, exiting...]"
    exit 1
fi

